version : "3.9"
services:
  front :
    image: "nadamankai/learn-room:frontend"
    ports:
      - "7000:80"
    depends_on:
      - back

  back:
    image: "nadamankai/learn-room:backend"
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "learn-room"



